version: "3.9"
services:
  test:
    image: tensorflow/tensorflow:latest-gpu
    command: python -c "import tensorflow as tf;tf.test.gpu_device_name()"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
                - gpu
                - utility # nvidia-smi
                - compute # CUDA. Required to avoid "CUDA version: N/A"
                - video   # NVDEC/NVENC. For instance to use a hardware accelerated ffmpeg. Skip it if you don't need it

  jupyterlab:
    build:
      context: ./jupyterlab-workspace
      dockerfile: ./Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token='41f1f99c-10be-43a8-b894-6f7341aa5c9a'
      --NotebookApp.password='41f1f99c-10be-43a8-b894-6f7341aa5c9a'
      --notebook-dir=/workspace
    ports:
      - 8888:8888
    volumes:
      - ./workspace:/workspace
      - ./workspace/user-settings:/home/jovyan/.jupyter/lab/user-settings
      - /home/akki/huggingface/rwkv/BlinkDL:/workspace/huggingface/BlinkDL
      - /tmp/cache:/home/jovyan/.cache

    # GPUを使う場合の設定
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
                - gpu
                - utility # nvidia-smi
                - compute # CUDA. Required to avoid "CUDA version: N/A"
                - video   # NVDEC/NVENC. For instance to use a hardware accelerated ffmpeg. Skip it if you don't need it
