version: "3.9"

services:
  jupyterlab:
    image: akkijp/jupyterlab-nginx:latest
    shm_size: 16gb
    restart: always
    command: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token='25kskfisha'
      --NotebookApp.password='25kskfisha'
      --notebook-dir=/workspace
    ports:
      - 80:80
      - 443:443
      - 8888:8888
      - 8000-8009:8000-8009
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/workbench/jovyan/.cache:/home/jovyan/.cache
      - ./workspace:/workspace
      - ./workspace/user-settings:/home/jovyan/.jupyter/lab/user-settings
      - /home/akki/github/akkijp/iris:/iris
      - /home/akki/.ssh:/home/jovyan/.ssh

    # GPUを使う場合の設定
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
                - gpu
                - utility # nvidia-smi
                - compute # CUDA. Required to avoid "CUDA version: N/A"
                - video   # NVDEC/NVENC. For instance to use a hardware accelerated ffmpeg. Skip it if you don't need it
