version: "3.9"
services:
  jupyterlab:
    build:
      context: ./jupyterlab
      dockerfile: ./Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    ports:
      - 8000:8888
    volumes:
      - ./jupyterlab/root_jupyter:/root/.jupyter
      - ./workspace:/workspace
      - ./workspace/user-settings:/home/jovyan/.jupyter/lab/user-settings

    # GPUを使う場合の設定
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
