version: "3.9"
services:
  editor:
    image: ghcr.io/eclipse-theia/theia-blueprint/theia-ide:1.51.0
    ports:
      - 3000:3000
    volumes:
      - ../:/home/project
    restart: always
    environment:
      - THEIA_WEBVIEW_EXTERNAL_ENDPOINT=http://192.168.3.12:3000
      - THEIA_MINI_BROWSER_HOST_PATTERN=http://192.168.3.12:3000
