build:
	# docker build node/node-16.19.1-alpine -t akkijp/node-16.19.1-alpine
	# docker build node/node-16.19.1-alpine -t akkijp/node-16.19.1-bullseye-slim
	docker build theia/next -t akkijp/theia-next

push:
	# docker push akkijp/node-16.19.1-alpine
	# docker push akkijp/node-16.19.1-bullseye-slim
	docker push akkijp/theia-next
