version: '3'
services:
  browserless:
    image: browserless/chrome:latest
    environment:
      - DEBUG=browserless:*
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=60000
      - MAX_QUEUE_LENGTH=20
      - HOST=0.0.0.0
      - PORT=3001
    container_name: "browserless"
    restart: always
    ports:
      - "3001:3001"
